env:
  browser: true
  es6: true
plugins:
  - 'jsdoc'
extends:
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
